### ISSUE TITLE
fatal error: fuzzy.h: No such file or directory during installation of ssdeep

### ISSUE THREAD

**Issue by iAbdullahMughal** [iAbdullahMughal/Sharingan#1]
During installation of ssdeep on ubuntu following exception observed!

> -----> Installing requirements with pip
>        Collecting identify (from -r /tmp/build_399a400d0656cb6c36e2c906f1a36f63/requirements.txt (line 2))
>          Downloading https://files.pythonhosted.org/packages/c1/b1/7586d30fea083c0b5b29561a1517771da511ec586dd50a5862ba0a63ec38/identify-1.1.8-py2.py3-none-any.whl
>        Collecting ssdeep (from -r /tmp/build_399a400d0656cb6c36e2c906f1a36f63/requirements.txt (line 3))
>          Downloading https://files.pythonhosted.org/packages/96/54/15b2e0b6e5042b67eb648e3d0e5d10105e6797353fe0a63579b74bf5eeee/ssdeep-3.3.tar.gz (347kB)
>            Complete output from command python setup.py egg_info:
>            zip_safe flag not set; analyzing archive contents...
>            pycparser.ply.__pycache__.lex.cpython-36: module references __file__
>            pycparser.ply.__pycache__.lex.cpython-36: module MAY be using inspect.getsourcefile
>            pycparser.ply.__pycache__.yacc.cpython-36: module references __file__
>            pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.getsourcefile
>            pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.stack
>            pycparser.ply.__pycache__.ygen.cpython-36: module references __file__
>            
>            Installed /tmp/pip-build-3d78szke/ssdeep/.eggs/pycparser-2.19-py3.6.egg
>            running egg_info
>            creating pip-egg-info/ssdeep.egg-info
>            writing pip-egg-info/ssdeep.egg-info/PKG-INFO
>            writing dependency_links to pip-egg-info/ssdeep.egg-info/dependency_links.txt
>            writing requirements to pip-egg-info/ssdeep.egg-info/requires.txt
>            writing top-level names to pip-egg-info/ssdeep.egg-info/top_level.txt
>            writing manifest file 'pip-egg-info/ssdeep.egg-info/SOURCES.txt'
>            src/ssdeep/__pycache__/_ssdeep_cffi_a52cfb2dx627c7d55.c:213:14: fatal error: fuzzy.h: No such file or directory
>                 #include "fuzzy.h"
>                          ^~~~~~~~~
>            compilation terminated.
>            Traceback (most recent call last):
>              File "/app/.heroku/python/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
>                extra_postargs)
>              File "/app/.heroku/python/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
>                spawn(cmd, dry_run=self.dry_run)
>              File "/app/.heroku/python/lib/python3.6/distutils/spawn.py", line 36, in spawn
>                _spawn_posix(cmd, search_path, dry_run=dry_run)
>              File "/app/.heroku/python/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
>                % (cmd, exit_status))
>            distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
>            
>            During handling of the above exception, another exception occurred:
>            
>            Traceback (most recent call last):
>              File "/tmp/pip-build-3d78szke/ssdeep/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 51, in _build
>                dist.run_command('build_ext')
>              File "/app/.heroku/python/lib/python3.6/distutils/dist.py", line 974, in run_command
>                cmd_obj.run()
>              File "/app/.heroku/python/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
>                _build_ext.run(self)
>              File "/app/.heroku/python/lib/python3.6/distutils/command/build_ext.py", line 339, in run
>                self.build_extensions()
>              File "/app/.heroku/python/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
>                self._build_extensions_serial()
>              File "/app/.heroku/python/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
>                self.build_extension(ext)
>              File "/app/.heroku/python/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
>                _build_ext.build_extension(self, ext)
>              File "/app/.heroku/python/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
>                depends=ext.depends)
>              File "/app/.heroku/python/lib/python3.6/distutils/ccompiler.py", line 574, in compile
>                self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
>              File "/app/.heroku/python/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
>                raise CompileError(msg)
>            distutils.errors.CompileError: command 'gcc' failed with exit status 1
>            
>            During handling of the above exception, another exception occurred:
>            
>            Traceback (most recent call last):
>              File "<string>", line 1, in <module>
>              File "/tmp/pip-build-3d78szke/ssdeep/setup.py", line 154, in <module>
>                ext_package="ssdeep",
>              File "/app/.heroku/python/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
>                return distutils.core.setup(**attrs)
>              File "/app/.heroku/python/lib/python3.6/distutils/core.py", line 148, in setup
>                dist.run_commands()
>              File "/app/.heroku/python/lib/python3.6/distutils/dist.py", line 955, in run_commands
>                self.run_command(cmd)
>              File "/app/.heroku/python/lib/python3.6/distutils/dist.py", line 974, in run_command
>                cmd_obj.run()
>              File "/app/.heroku/python/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 278, in run
>                self.find_sources()
>              File "/app/.heroku/python/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 293, in find_sources
>                mm.run()
>              File "/app/.heroku/python/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 524, in run
>                self.add_defaults()
>              File "/app/.heroku/python/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 560, in add_defaults
>                sdist.add_defaults(self)
>              File "/app/.heroku/python/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
>                self._add_defaults_python()
>              File "/app/.heroku/python/lib/python3.6/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
>                build_py = self.get_finalized_command('build_py')
>              File "/app/.heroku/python/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
>                cmd_obj.ensure_finalized()
>              File "/app/.heroku/python/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
>                self.finalize_options()
>              File "/app/.heroku/python/lib/python3.6/site-packages/setuptools/command/build_py.py", line 34, in finalize_options
>                orig.build_py.finalize_options(self)
>              File "/app/.heroku/python/lib/python3.6/distutils/command/build_py.py", line 45, in finalize_options
>                ('force', 'force'))
>              File "/app/.heroku/python/lib/python3.6/distutils/cmd.py", line 287, in set_undefined_options
>                src_cmd_obj.ensure_finalized()
>              File "/app/.heroku/python/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
>                self.finalize_options()
>              File "/tmp/pip-build-3d78szke/ssdeep/setup.py", line 22, in finalize_options
>                self.distribution.ext_modules = get_ext_modules()
>              File "/tmp/pip-build-3d78szke/ssdeep/setup.py", line 77, in get_ext_modules
>                binding.verify()
>              File "/tmp/pip-build-3d78szke/ssdeep/src/ssdeep/binding.py", line 125, in verify
>                libraries=self._libraries,
>              File "/tmp/pip-build-3d78szke/ssdeep/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/api.py", line 451, in verify
>                lib = self.verifier.load_library()
>              File "/tmp/pip-build-3d78szke/ssdeep/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/verifier.py", line 104, in load_library
>                self._compile_module()
>              File "/tmp/pip-build-3d78szke/ssdeep/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/verifier.py", line 201, in _compile_module
>                outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
>              File "/tmp/pip-build-3d78szke/ssdeep/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 22, in compile
>                outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
>              File "/tmp/pip-build-3d78szke/ssdeep/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 58, in _build
>                raise VerificationError('%s: %s' % (e.__class__.__name__, e))
>            cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
>            
>            ----------------------------------------
>        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3d78szke/ssdeep/

This exception is revoking installation of ssdeep library from pip.

**Comment by iAbdullahMughal** [comment]
To resolve this issue you may need to install **libfuzzy-dev** package in ubuntu. Command as follows
`apt-get -y install libfuzzy-dev`

Add sudo if required.
